# serverless.yml

service: senti-tweet

provider:
  name: aws
  runtime: python3.6

functions:
  get-tweet:
    handler: handler.main


# serverless.yml

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
